### PR TITLE
Adds caching to vulnerable API call

### PR DESCRIPTION
**Pull request by nikooo777**
This PR adds caching to a LBRYCRD call that takes 4 seconds to execute.
Additionally the QR library is updated and the SQL skeleton is updated.

### CODE REVIEW

**Comment by nikooo777** [comment]
this PR also reverts the update to the cakePHP library.

**Comment by tzarebczan** [comment]
Can we get this merged soon, along with the other PR?

**Comment by nikooo777** [comment]
@tzarebczan just so you know, the current explorer server is running this branch IIRC.

**Comment by nikooo777** [comment]
I need this in master. I'll merge it myself. if something is wrong please revert the commit and correct it.

**Pull request merged**
